name: disk

services:
  rails_app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile

    tty: true
    stdin_open: true

    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
      - HISTFILE=/home/rails/disk/tmp/.bash_history
      - HISTSIZE=10000
      - SAVEHIST=10000

    ports:
      - "3000:3000"

    volumes:
      - ../:/app
      - bundle_cache:/usr/local/bundle
      - ../disk/tmp/node_modules:/app/disk/node_modules
      - ../disk/tmp/.bash_history:/home/rails/disk/tmp/.bash_history

    working_dir: /app/disk
    command: sleep infinity
volumes:
  bundle_cache:
